;;; general arguments (used for eeprom, must be globally addressable)
#define arg1          0x70
#define arg2          0x71

;;; lcd.asm
#define lcd_tmr0 0x60
#define lcd_tmr1 0x61
#define lcd_pos 0x62
#define lcd_tmp 0x63
#define lcd_arg 0x64
#define lcd_data0 0x50
#define lcd_data1 0x51
#define lcd_data2 0x52
#define lcd_data3 0x53
#define lcd_data4 0x54
#define lcd_data5 0x55
#define lcd_data6 0x56
#define lcd_data7 0x57
#define lcd_data8 0x58
#define lcd_data9 0x59
#define lcd_dataA 0x5a
#define lcd_dataB 0x5b
#define lcd_dataC 0x5c
#define lcd_dataD 0x5d
#define lcd_dataE 0x5e
#define lcd_dataF 0x5f

;;; serial.asm
#define serial_timeout_0 0xb0
#define serial_timeout_1 0xb1
#define serial_timeout_2 0xb2
#define serial_work_tmp  0xb3
#define serial_work_tmp2 0xb4

